server:
  port: 8086
  error:
    include-message: always

spring:
  data:
    mongodb:
      uri: mongodb://192.168.232.130:10500/businessbanking
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8099/eureka

