server:
  port: 8089

eureka:
  instance:
    instance-id: ${spring:application:name}:${random:uuid}
  client:
    serviceUrl:
      defaultZone: http://localhost:8099/eureka
spring:
  application:
    name: apigateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: CREDIT_MICROSERVICE
          uri: lb://CREDIT_MICROSERVICE
          predicates:
            - Path=/api/credit/**
        - id: MOVEMENT_MICROSERVICE
          uri: lb://MOVEMENT_MICROSERVICE
          predicates:
            - Path=/api/movement/**
        - id: CLIENT_MICROSERVICE
          uri: lb://CLIENT_MICROSERVICE
          predicates:
            - Path=/api/client/**
        - id: ACCOUNT_MICROSERVICE
          uri: lb://ACCOUNT_MICROSERVICE
          predicates:
            - Path=/api/account/**