server:
  port: 8089
  error:
    include-message: always
spring:
  application:
    name: apigateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: CREDIT-SERVICE
          uri: lb://CREDIT-SERVICE
          predicates:
            - Path=/api/credit/**
        - id: MOVEMENT-SERVICE
          uri: lb://MOVEMENT-SERVICE
          predicates:
            - Path=/api/movement/**
        - id: CLIENT-SERVICE
          uri: lb://CLIENT-SERVICE
          predicates:
            - Path=/api/client/**
        - id: ACCOUNT-SERVICE
          uri: lb://ACCOUNT-SERVICE
          predicates:
            - Path=/api/account/**
eureka:
  instance:
    instance-id: ${spring:application:name}:${random:uuid}
  client:
    serviceUrl:
      defaultZone: http://localhost:8099/eureka