server:
  port: 8089
  error:
    include-message: always
spring:
  application:
    name: apigateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: CREDIT-SERVICE
          uri: http://192.168.232.130:8087
          predicates:
            - Path=/api/credit/**
        - id: MOVEMENT-SERVICE
          uri: http://192.168.232.130:8088
          predicates:
            - Path=/api/movement/**
        - id: CLIENT-SERVICE
          uri: http://192.168.232.130:8085
          predicates:
            - Path=/api/client/**
        - id: ACCOUNT-SERVICE
          uri: http://192.168.232.130:8086
          predicates:
            - Path=/api/account/**
eureka:
  instance:
    instance-id: ${spring:application:name}:${random:uuid}
  client:
    serviceUrl:
      defaultZone: http://192.168.232.130:8099/eureka