server:
  port: 8088
  error:
    include-message: always
my:
  property:
    ip: localhost
spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/businessbanking
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8099/eureka
management:
  health:
    circuitbreakers:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
resilience4j:
  circuitbreaker:
    instances:
      movement:
        registerHealthIndicator: true
        eventConsumerBufferSize: 10
        slidingWindowType: COUNT_BASED
        slidingWindowSize: 5
        failureRateThreshold: 5
        waitDurationInOpenState: 5s
        permittedNumberOfCallsInHalfOpenState: 3
        automaticTransitionFromOpenToHalfOpenEnabled: true